# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-18 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('cmd_peru', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_birth', models.DateField(blank=True, null=True)),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('midoc_user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_specialist', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enabled', models.NullBooleanField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='EmergencyAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attention_type_id', models.CharField(blank=True, max_length=80, null=True)),
                ('attention_name', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('is_enabled', models.NullBooleanField()),
                ('is_emergency', models.NullBooleanField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'emergency_attention',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_level', models.IntegerField(blank=True, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('web_page', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comercial_activity', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('midoc_user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'enterprise',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('final_date', models.DateField(blank=True, null=True)),
                ('access_number', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'license',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('is_enabled', models.NullBooleanField()),
                ('postal_address', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='LocationEmergencyAttention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'location_emergency_attention',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('medical_history_text', models.TextField(blank=True, null=True)),
                ('symptom', models.TextField(blank=True, null=True)),
                ('doctor_comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'medical_history',
            },
        ),
        migrations.CreateModel(
            name='MedicalHistoryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'medical_history_media',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_birth', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('midoc_user', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('picture_url', models.TextField(blank=True, null=True)),
                ('blood_type', models.TextField(blank=True, null=True)),
                ('allergic_reaction', models.TextField(blank=True, null=True)),
                ('token_sinch', models.CharField(blank=True, max_length=100, null=True)),
                ('nokia_weight', models.CharField(blank=True, max_length=10, null=True)),
                ('nokia_body_temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('nokia_blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('is_enterprise_enabled', models.NullBooleanField()),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('last_modified_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'patient',
            },
        ),
    ]
